### ISSUE TITLE
Bad data after export cannot open sheet

### ISSUE THREAD

**Issue by estevan83** [AlanBell/LSWYSIWYG#6]
Hi Alan,
when I export and open file in exel is give me wrong data 

![image](https://cloud.githubusercontent.com/assets/9391848/20786274/3c8c6938-b7a5-11e6-95b5-662d812e06e6.png)

tahnks in advance

**Comment by AlanBell** [comment]
interesting, looks like an incorrect character set somehow. Does this happen for all list views, is it some special character that triggers it? Is it the language (does it work if you flip to English?)

**Comment by estevan83** [comment]
yes every time i try to export data, in all modules!!! :(

I think to have found the solution
in file action/ViewToSheet.php  at the end of file i've added ob_end_clean(); and now works well
in every module, for each user and with several languages!!
```
// add this line
//**************
ob_end_clean();
//***************
// end of new line
    if(isset($_SERVER['HTTP_USER_AGENT']) && strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE')) {
            header('Pragma: public');
            header('Cache-Control: must-revalidate, post-check=0, pre-check=0');
    }

    header('Content-Type: application/x-msexcel');
    header('Content-Length: '.@filesize($tempFileName));
    $filename=decode_html($customView->get('viewname')) . ".xls";
    header('Content-disposition: attachment; filename="'.$filename.'"');

    $fp = fopen($tempFileName, 'rb');
    fpassthru($fp);
  }
}
```

**Comment by AlanBell** [comment]
interesting, any idea why that works? What prompted you to add that? It sounds like something I should add to the code, but I am not sure what it is doing.

**Comment by estevan83** [comment]
after googleing i've found these solutions

please refere here:
http://stackoverflow.com/questions/16984132/phpexcel-file-format-or-extension-is-not-valid
http://stackoverflow.com/questions/14252465/phpexcel-file-cannot-open-file-because-the-file-format-or-file-extension-is-not

I think there is something of  extra  in buffer that is downloaded but that is not part of the document and therefore does not open, I think it does not depend on the particular character because the problem is always repeated
